ci: don't install LLVM/clang
It simply stops working every now an again with the following error:
    ==> Installing dependencies for llvm: python@3.11 and z3
    ==> Installing llvm dependency: python@3.11
    ==> Downloading https://ghcr.io/v2/homebrew/core/python/3.11/manifests/3.11.6_1
    Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/481941c47c71dfeb6fba3057ead9b0bd21f7ca514b815bd8dde7cbeff257b362--python@3.11-3.11.6_1.bottle_manifest.json
    ==> Pouring python@3.11--3.11.6_1.monterey.bottle.tar.gz
    Error: The `brew link` step did not complete successfully
    The formula built, but is not symlinked into /usr/local
    Could not symlink bin/2to3
    Target /usr/local/bin/2to3
    already exists. You may want to remove it:
      rm '/usr/local/bin/2to3'

I've tried multiple approaches but none of them work. Besides, I don't
think we use brew LLVM atm, because CMake detects AppleClang by default.

Similar thing on Linux, since we don't manually override it, GCC is used
by default.

Signed-off-by: Daniil Tatianin <99danilt@gmail.com>